### ISSUE TITLE
[BUG] secure value security claims

### ISSUE THREAD

**Issue by raggi** [crazywolf132/secretfetch#1]
the readme claims that secure mode has zero-copy and zeroing behavior, but the implementation:

- copies set parameters into slices
- creates new slices on sequential sets leaking the old slice into the GC which has an unknowable lifetime (may be forever)
- copies values on get

this implementation is probably reasonable given Go constraints (though the zeroing behavior on clear is a bit superfluous given the behavior of set), but it does not align with the claims

i ended up looking because meeting the claims in a GC'd environment is tricky, so i was curious how far you'd gone!

**Comment by binbandit** [comment]
Great call out.
I have updated the claims, and adjusted some code to be more careful around zeroing.
I have also updated the guides to be more transparent about the limitations of the go programming language.
